### ISSUE TITLE
ExactSumConstraint erroneously removes valid domains in preProcess

### ISSUE THREAD

**Issue by erydo** [DanielCasner/python-constraint#1]
The constraint assumes only positive domains, which is an invalid (or at least, unstated) assumption.

```python
from constraint import Problem, ExactSumConstraint

problem = Problem()
problem.addVariable("a", [-3, -2, -1, 0, 1, 2, 3])
problem.addVariable("b", [-3, -2, -1, 0, 1, 2, 3])
problem.addConstraint(ExactSumConstraint(0))

print problem.getSolutions()
```

Actual result:
```py
[{'a': 0, 'b': 0}]
```

Expected result:
```py
[{'a': -3, 'b': 3}, {'a': -2, 'b': 2}, {'a': -1, 'b': 1}, {'a': 0, 'b': 0}]
```

**Comment by DanielCasner** [comment]
Thanks for the comment. This repository is a fork of a project which is now in pypi. You should reference that version instead and report bugs to it's maintainers.
https://pypi.python.org/pypi/python-constraint
